spring:
  jackson:
    time-zone: Asia/Seoul

  application:
    name: fintest-server

 datasource:
   driver-class-name: org.mariadb.jdbc.Driver
   url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${FINTEST_DB_NAME}
   username: ${DB_USER}
   password: ${DB_PASS}



  jpa:
    hibernate:
      ddl-auto: ${DDL_TYPE}
#    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.jdbc.time_zone: Asia/Seoul

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    db:
      enabled: true
    redis:
      enabled: true

jwt:
  public-key : ${JWT_PUBLIC_KEY}


server:
  port: ${FINTEST_SERVER_PORT}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

